apiVersion: v1
kind: Secret
metadata:
  name: registrysecret
  annotations:
    "helm.sh/hook": pre-install
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuY29ycC5tb3RpdiI6eyJ1c2VybmFtZSI6Im50ZC1naXRsYWIiLCJwYXNzd29yZCI6IjVGUUg2emVXM3VUUTVjc1IiLCJhdXRoIjoiYm5Sa0xXZHBkR3hoWWpvMVJsRklObnBsVnpOMVZGRTFZM05TIn19fQ==
