apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: health
    port: {{pluck $.Values.global.env .Values.envs.WEB_PORT | first | default .Values.envs.WEB_PORT._default}}
    protocol: TCP
  - name: metrics
    port: {{pluck $.Values.global.env .Values.envs.PROMETHEUS_PORT | first | default .Values.envs.PROMETHEUS_PORT._default}}
    protocol: TCP
  type: ClusterIP
